### ISSUE TITLE
HTML to PDF Images not showing

### ISSUE THREAD

**Issue by skynetishere** [Invoicebus/html-invoice-generator#11]
HTML to PDF Images not showing
![dvs](https://user-images.githubusercontent.com/49785510/56423787-a2aec780-62a5-11e9-9f98-79a518538847.png)

**Comment by bitconym** [comment]
It depends on the browser you used to save the PDF, so you need to enable to print background graphics.

On Google Chrome, on the print windows open "More Settings", make sure you uncheck "Headers and footers" and check "Background graphics" as in the image below:

![image](https://user-images.githubusercontent.com/590260/56423967-a004a000-62ae-11e9-911b-8d663831e9cd.png)
