### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by weberro** [Invoicebus/html-invoice-generator#5]
"Bill to" should be "Rechnung für" (instead of "GESETZESENTWURF FÜR:").
"Due Date" should be "Fälligkeitsdatum" (instead of "GEBURTSTERMIN").

Date format could be automatically applied for the corresponding country / language (german format 'dd.mm.yyyy').

**Comment by imjustd** [comment]
Fixed the German text, as for the date format it's a nice feature and we'll have it on our minds. Note that once you save the invoice data, the saved data format will be applied in future for all invoices.
