### ISSUE TITLE
Building not possible due to missing "compass" dependency

### ISSUE THREAD

**Issue by pylight** [Invoicebus/html-invoice-generator#8]
Hi,
Note: I'm not very experienced with node/npm, so I might have done something wrong as well ;) 

I tried to build the latest version (grunt dev), but this failed on my system (Ubuntu 16.04.3 LTS), here's my output:

    ╰─$ grunt dev --force                                                                                          3 ↵
    Running "clean:build" (clean) task
    >> 1 path cleaned.

    Running "clean:fonts" (clean) task
    >> 0 paths cleaned.

    Running "jshint:src" (jshint) task

    ✔ No problems

    Running "concat:js" (concat) task
    File dist/generator.js created.

    Running "compass:dev" (compass) task
    Warning: not found: compass Used --force, continuing.

    Running "compass:tpl_dev" (compass) task
    Warning: not found: compass Used --force, continuing.

    Running "copy:tpl" (copy) task
    Copied 5 files

    Running "replace:dev" (replace) task
    Replace dist/generator.js → dist/generator.js
    Replace dist/template.html → dist/template.html

    Running "copy:fonts" (copy) task
    Copied 19 files

    Running "copy:lang" (copy) task
    Copied 5 files

    Running "copy:docs" (copy) task
    Created 3 directories, copied 15 files

    Done, but with warnings.

    Execution Time (2018-01-04 15:54:36 UTC+1)
    loading tasks  772ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 35%
    jshint:src      1.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 61%
    Total 2.2s

It didn't produce a usable template.html file of course. When googling for the issue, I've found https://stackoverflow.com/questions/19752937/compassserver-not-found-when-running-grunt-server and tried "npm install -g compass" which did not help. However, installing it via "gem install compass" worked and afterwards I could use successfully.

**Comment by imjustd** [comment]
Yes, you're right, you need to install `compass` with the `gem install compass` command, as `compass` is a Ruby gem. I'm glad you sorted this out.
