### ISSUE TITLE
Blank white screen

### ISSUE THREAD

**Issue by nichwyto** [Invoicebus/html-invoice-generator#9]
Hi I have tried to start an invoice for a client but the page which was working great yesterday just stopped working all of a sudden. 

I open the file in chrome, safari, firefox and it all loads a blank white screen. When the window opens it flashes a quick glance of the invoice but then loads blank. I know the code is still in the file, it is just not displaying correctly. Any suggestions? I even restarted the computer, and updated my browser.

<img width="1097" alt="screen shot 2018-01-16 at 10 19 27 pm" src="https://user-images.githubusercontent.com/2141031/35028608-c3ab4f92-fb0b-11e7-85b3-f70a291ad8e1.png">
<img width="1366" alt="screen shot 2018-01-16 at 10 19 17 pm" src="https://user-images.githubusercontent.com/2141031/35028610-c524445a-fb0b-11e7-9671-56a88858a7e2.png">

**Comment by imjustd** [comment]
Please find my answers on our official support forum for the templates https://groups.google.com/forum/#!topic/html-invoice-generator/XImHmhJMsrU. Github repo issues are used only for bugs in the template generator script.
